language: go
sudo: false
go:
  - "1.11"
before_install:
  - go get github.com/mattn/goveralls
script:
  - go build
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then go test -v ./... -covermode=count -coverprofile=coverage.out; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then $GOPATH/bin/goveralls -v -coverprofile=coverage.out -service=travis-ci; fi'
